### ISSUE TITLE
BIMI Inspector May Be Too Greedy

### ISSUE THREAD

**Issue by toddherr** [pepipost/BIMI-official#3]
It has been mentioned that the BIMI Inspector tool on the bimigroup.org website (https://bimigroup.org/bimi-generator/) may be flagging condition that shouldn’t be flagged.

Sample domain - response.talktalkbusiness.co.uk

Results include the following text:

**VMC Certificate File Issues You Need To Fix**

_Warning: The X.509 certificate provided is not valid for the purposes of client auth, server auth_

The language about the cert not being valid for client auth, server auth was confusing.

It was also noted that this domain had some SVG image issues which were noted by the BIMI Inspector, but no one knew whether or not the SVG image issues triggered the report of VMC issues.

**Comment by Hiteshpandey** [comment]
Hi @toddherr,
We have disabled the extended certificate checks for now, so you won't be getting these errors.
The SVG and VMC checks are not co-dependent. So failure in the VMC checks won't effect the SVG report.
