### ISSUE TITLE
Evidence documents do not require the .pem extension

### ISSUE THREAD

**Issue by notbrokenjemma** [pepipost/BIMI-official#6]
```
        regex_cert = r"v=BIMI1;(?=.*(l=((.*):\/\/(.*.svg|.*.SVG)))\b)(?=.*(a=((.*):\/\/(.*.pem|.*.PEM)))\b).*(;$| |$)"
        regex_without_cert = r"v=BIMI1;(|\s+)l=((.*):\/\/(.*.svg|.*.SVG))(;| |).*"
```

.pem is not a required extension, I have also seen these extensions capitalized as Svg in the wild, which would fail the regex.

**Comment by Hiteshpandey** [comment]
Updated the extension checks. We have kept the .pem extension check, until further confirmation on BIMI.
